//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroNET.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Contrato
    {
        public Contrato()
        {
        }

        public int Id { get; set; }
        public string DataContrato { get; set; }
        public string DataVigencia { get; set; }
        public int ClienteId { get; set; }
        public int ProdutoId { get; set; }
        public int FaixaPrecoId { get; set; }
        public int DiaBasePagamento { get; set; }
        public Nullable<System.DateTime> UltimoPagamento { get; set; }
        public Nullable<int> NumeroContrato { get; set; }
        public int Servidores { get; set; }
        public string Observacoes { get; set; }
        public int UsuariosLicenciados { get; set; }
    }
}
