//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroNET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FaixaPreco
    {
        public FaixaPreco()
        {
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public decimal Preco { get; set; }
        public int Usuarios { get; set; }
        public int Documentos { get; set; }
        public decimal PrecoUsuarioAdicional { get; set; }
        public decimal PrecoDocumentoAdicional { get; set; }
    }
}
