//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroNET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servidor
    {
        public int Id { get; set; }
        public string CPUID { get; set; }
        public string Nome { get; set; }
        public string OS { get; set; }
        public string Memoria { get; set; }
        public bool Autorizado { get; set; }
        public int ContratoId { get; set; }
        public int UsuariosEmUso { get; set; }
    }
}
